DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR NOT NULL,
    content TEXT NOT NULL,
    urgency VARCHAR NOT NULL DEFAULT LOW,
    complete INTEGER NOT NULL DEFAULT 0,
    task_type VARCHAR NOT NULL DEFAULT PERSONAL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);